### ISSUE TITLE
Windows based MakeFile Needed

### ISSUE THREAD

**Issue by eagertolearn1** [hwstar/FW-AC-Emeter-ESP8266#1]
Hello,
Thanks for the Wonderful Work !!
As mentioned in the description section that you have Windows Based Makefile as well.
Can you please share that as well . It will be of great help.

Thanks and Regards

**Comment by hwstar** [comment]
Hello, there isn't a windows based makefile for this. I don't run windows, so I would not be able to create such a file. 

The message for the ESP8266 firmware states the following:

"NB:Current Makefile supports Linux build hosts only at this time. If someone wants to submit a working Makefile for Windows, I'd be happy to add it to the repository."

Steve
